#!/bin/sh

xset +fp /home/kzer-za/.fonts &
xset fp rehash &

dunst &
socat -d -d pty,raw,echo=0,link=/tmp/lemonbarin pty,raw,echo=0,link=/tmp/lemonbarout &

bspc config border_width        0
bspc config window_gap          0

bspc config top_padding         0
bspc config bottom_padding      24

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled split_ratio="0.2"

sleep 0.5s
cat /tmp/lemonbarin | lemonbar -p -g 1920x24+0+0 -d -o 0 -f "ypn envypn" -o \-1 -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1' -b -B \#FF0f0403 -u 2 &
python ~/start_new_panel.py &
unclutter -root &
