#! /bin/sh

socat -d -d pty,raw,echo=0,link=/tmp/lemonbarin pty,raw,echo=0,link=/tmp/lemonbarout &

bspc config border_width        2
bspc config window_gap          8

bspc config top_padding         40

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor DVI-D-1 -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sleep 0.5s
sh ~/lemons.sh &
cat /tmp/lemonbarin | lemonbar -p -g 1912x32+8+8 -d -f "ypn envypn" -f FontAwesome-10 &
unclutter -root &
