#! /bin/sh

bspc config border_width        2
bspc config window_gap          8

bspc config top_padding         40

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor DVI-D-1 -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sh ~/lemon.sh | lemonbar -p -g 784x32+8+8 -d -f "ypn envypn"
