#!/usr/bin/python

import imaplib

mail = imaplib.IMAP4_SSL()
(retcode, capabilities) = mail.login() #hahaha no password for you
mail.list()
mail.select('inbox')

(retcode, messages) = mail.search(None, '(UNSEEN)')
if retcode == 'OK':
    print(len(messages[0].split()))
else:
    print("null")

